pull_request_rules:
  - name: evil-auto-merge
    conditions:
      - base=main
    actions:
      merge: {}
  - name: evil-dismiss-reviews
    conditions:
      - base=main
    actions:
      dismiss_reviews: {}
